name: ddm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.7
  - pip=19.1.1

  - pytorch=1.7.0
  - torchvision=0.8
  - cryptography=3.1.1
  - pip:
      - ray==1.0.0
      - dataclasses==0.6
      - black==19.10b0
      - joblib==0.17.0
      - keras==2.4.3
      - scikit-learn==0.23.2
      - scikit-optimize==0.8.1
      - skorch==0.9.0
      - tensorboard==2.3.0
      - tensorflow==2.3.1
      - tensorflow-estimator==2.3.0
      - microsoft-bonsai-api==0.1.2
      - bonsai-cli==1.0.4
      - pandas==1.1.4
      - pyyaml==5.3.1
      - pytest==6.2.1
      - scipy==1.5.4
      - h5py==2.10.0
      - nbgrader==0.6.1
      - tune-sklearn==0.1.0
      - hyperopt==0.2.5
      - lightgbm==3.1.1
      - xgboost==1.3.0.post0
      - python-dotenv==0.15.0
      - hydra-core==1.0.5
      - natsort==7.1.0
