name: datadriven
dependencies:
- python=3.7
- pip=19.1.1
- jupyter=1.0.0
- matplotlib=3.0.3
- seaborn=0.9.0
- plotly=3.10.0
- scipy=1.3.0
- pandas=0.25.1
- numpy=1.16.4
- pip:
  - bonsai-cli==0.9.12
  - bonsai-gym==2.0.13
  - bonsai-ai==2.2.8
  - cufflinks==0.16
  - joblib==0.13.2
  - keras==2.2.4
  - keras-applications==1.0.8
  - keras-preprocessing==1.1.0
  - scikit-learn==0.21.3
  - tensorboard==1.14.0
  - tensorflow==1.14.0
  - tensorflow-estimator==1.14.0
  - vpython==7.5.1